name: nn-ert-infiltration
channels:
- defaults
dependencies:
- numpy=1.26
- pillow
- python=3.10
- scikit-learn=1.3
- scipy[version='<1.13']
- pandas
- ffmpeg
- opencv
- pip:
  - aiohappyeyeballs==2.6.1
  - aiohttp==3.13.2
  - aiosignal==1.4.0
  - anyio==4.11.0
  - argon2-cffi==25.1.0
  - argon2-cffi-bindings==25.1.0
  - arrow==1.4.0
  - asttokens==3.0.0
  - async-timeout==5.0.1
  - attrs==25.4.0
  - beautifulsoup4==4.14.2
  - bleach==6.3.0
  - certifi==2025.10.5
  - cffi==2.0.0
  - charset-normalizer==3.4.4
  - cmcrameri==1.9
  - cmocean==4.0.3
  - colorama==0.4.6
  - colorcet==3.1.0
  - comm==0.2.3
  - contourpy==1.3.2
  - cycler==0.12.1
  - debugpy==1.8.17
  - decorator==5.2.1
  - defusedxml==0.7.1
  - exceptiongroup==1.3.0
  - executing==2.2.1
  - fastjsonschema==2.21.2
  - filelock==3.19.1
  - fonttools==4.60.1
  - fqdn==1.5.1
  - frozenlist==1.8.0
  - fsspec==2025.9.0
  - idna==3.11
  - imageio==2.37.0
  - iniconfig==2.3.0
  - ipykernel==7.1.0
  - ipython==8.37.0
  - ipywidgets==8.1.8
  - isoduration==20.11.0
  - jedi==0.19.2
  - Jinja2==3.1.6
  - jsonpointer==3.0.0
  - jsonschema==4.25.1
  - jsonschema-specifications==2025.9.1
  - jupyter-events==0.12.0
  - jupyter_client==8.6.3
  - jupyter_core==5.9.1
  - jupyter_server==2.17.0
  - jupyter_server_proxy==4.4.0
  - jupyter_server_terminals==0.5.3
  - jupyterlab_pygments==0.3.0
  - jupyterlab_widgets==3.0.16
  - kiwisolver==1.4.9
  - lark==1.3.1
  - markdown-it-py==4.0.0
  - MarkupSafe==2.1.5
  - matplotlib==3.10.7
  - matplotlib-inline==0.2.1
  - mdurl==0.1.2
  - meshio==5.3.5
  - mistune==3.1.4
  - mkl-service==2.4.0
  - more-itertools==10.8.0
  - mpmath==1.3.0
  - msgpack==1.1.2
  - multidict==6.7.0
  - nbclient==0.10.2
  - nbconvert==7.16.6
  - nbformat==5.10.4
  - nest-asyncio==1.6.0
  - networkx==3.3
  - opencv-python==4.7.0
  - overrides==7.7.0
  - pandocfilters==1.5.1
  - parso==0.8.5
  - pgcore==1.5.0
  - platformdirs==4.5.0
  - pluggy==1.6.0
  - pooch==1.8.2
  - prometheus_client==0.23.1
  - prompt_toolkit==3.0.52
  - propcache==0.4.1
  - psutil==7.1.3
  - pure_eval==0.2.3
  - pycparser==2.23
  - pygimli==1.5.4
  - Pygments==2.19.2
  - pyparsing==3.2.5
  - pytest==8.4.2
  - python-json-logger==4.0.0
  - pyvista==0.46.4
  - pywinpty==3.0.2
  - PyYAML==6.0.3
  - pyzmq==27.1.0
  - referencing==0.37.0
  - requests==2.32.5
  - rfc3339-validator==0.1.4
  - rfc3986-validator==0.1.1
  - rfc3987-syntax==1.1.0
  - rich==14.2.0
  - rpds-py==0.28.0
  - scooby==0.11.0
  - Send2Trash==1.8.3
  - simpervisor==1.0.0
  - sniffio==1.3.1
  - soupsieve==2.8
  - stack-data==0.6.3
  - sympy==1.14.0
  - terminado==0.18.1
  - tetgen==0.6.7
  - tinycss2==1.4.0
  - tomli==2.3.0
  - torch==2.9.0+cpu
  - torchaudio==2.9.0+cpu
  - torchvision==0.24.0+cpu
  - tornado==6.5.2
  - tqdm==4.67.1
  - traitlets==5.14.3
  - trame==3.12.0
  - trame-client==3.11.2
  - trame-common==1.0.1
  - trame-server==3.8.1
  - trame-vtk==2.10.0
  - trame-vuetify==3.1.0
  - typing_extensions==4.15.0
  - uri-template==1.3.0
  - urllib3==2.5.0
  - vtk==9.5.2
  - wcwidth==0.2.14
  - webcolors==25.10.0
  - webencodings==0.5.1
  - websocket-client==1.9.0
  - widgetsnbextension==4.0.15
  - wslink==2.5.0
  - yarl==1.22.0
