name: nn-ert-infiltration
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - numpy>=2.1
  - scipy>=1.11
  - pandas
  - scikit-learn
  - matplotlib
  - meshio
  - ipykernel
  - pytorch
  - cpuonly
  - pip
  - pip:
      - pygimli==1.5.4
      - tetgen==0.6.7
